install.packages("ggplot2", repos="http://cran.rstudio.com/")
install.packages("jsonlite", repos="http://cran.rstudio.com/")
install.packages("devtools", repos="http://cran.rstudio.com/")
install.packages("R.oo", repos="http://cran.rstudio.com/", dependencies = TRUE)
install.packages("plyr", repos = "http://cran.rstudio.com/")
